### ISSUE TITLE
annoying toast notifications

### ISSUE THREAD

**Issue by SafeSlingerProject** [SafeSlingerProject/SafeSlinger-Android#135]
The app background is toasting "internet not available" when the app is not in the foreground and in airplane mode, which is frustrating for users since its hard to know which application is toasting the notification.

**Comment by mwfarb** [comment]
Removed in https://github.com/SafeSlingerProject/SafeSlinger-Android/commit/00e1c917acd3241115dd7e2b856e02396b5edd09.
