### ISSUE TITLE
inconsistent operation of activity back stack

### ISSUE THREAD

**Issue by mwfarb** [SafeSlingerProject/SafeSlinger-Android#28]
User Reports:
- I encountered a weird state in my SafeSlinger. When I wanted to send a message, I selected the recipient, but when I clicked on the person, the to field stayed empty. I then went to the messages screen and tried to type a message there, but when I hit send, the message would not be sent and the text stayed there. There was no error message. At the same time, I could receive messages. I then rebooted the phone and thereafter everything worked again, except that it took a very long time for the other phone to receive the message, not sure how long but more than several minutes ... both devices were Android phones.
- I could not enter passphrase but the app still let me in then did not let me view my messages because no passphrase was entered but I could not get back to the passphrase screen

**Comment by SafeSlingerProject** [comment]
Another user report: I entered my password a few minutes ago, so it was expired. When I clicked on the icon, I got to the messages screen and saw all the messages with Bob. I thought it was odd that I was not asked for the password. I then entered a message, and when I clicked send I got an error that the password was stale but I didn't see how to enter it. I clicked around for a while without success. Eventually I closed SafeSlinger and then I was asked about it. The message I typed disappeared.
