### ISSUE TITLE
Action Bar Menus All Black

### ISSUE THREAD

**Issue by SafeSlingerProject** [SafeSlingerProject/SafeSlinger-Android#92]
Google Play: "The menu (three dots) on the top right corner option is all black. Can it be made white?" Android 5.0

**Comment by mwfarb** [comment]
This may be from the Android 5.0 default themes. We may need another Theme filter for all screens API 21 and above.

**Comment by mwfarb** [comment]
Added by @JW-Vinay  in 927b975
