### ISSUE TITLE
force stop error on startup

### ISSUE THREAD

**Issue by SafeSlingerProject** [SafeSlingerProject/SafeSlinger-Android#99]
From Google Play: "Great concept but can sometimes crash"
"This app is great, so easy it can bring crypto to computer illiterate people (the kind that can barely operate a Mac) and the key slinging process is straightforward. However... on my Galaxy S5 SM-G900M I had to clear all my data before getting it to work, as the app would force stop as soon as I opened it. As a result, this app for now requires backing up often, which can only be done with a rooted phone, which means a huge security hole must be opened in order to close the hole of insecure messaging."

App version 1.8.1.2
Galaxy S5 (klte)

**Comment by SafeSlingerProject** [comment]
Issue https://github.com/SafeSlingerProject/SafeSlinger-Android/issues/96 occurred on the same model of device, albeit in the Exchange process, not the startup process. But perhaps the same issues are occurring in several activities.

**Comment by mwfarb** [comment]
Corrected in 1.8.2 for the probable crash, but there was one other error, OutOfMemory error in the play store at this time, with 1 line of stack trace only, and for the android package, not even edu.* for us. The OS decided our app needed to be closed to make memory for other apps, nothing we can do about this.
